name: CI
on:
  push:
  pull_request: 

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm 
      uses: pnpm/action-setup@v4 # use the version in packageManger field from package.json
    - name: Use Node.js version from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build app
      run: pnpm migrate:prod && pnpm generate && pnpm build
    - name: Run unit tests
      run: pnpm test